---
title: "Topic Classification for Citizen Complaints: A Case Study for Istanbul"
output: html_document
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3 {
  text-align: center;
}
```

### Project Overview 

Beyaz Masa, complaint desk of Istanbul Metropolitan Municipality, is constantly loaded with volumes of complaints written for various matters via different platforms. Only in May 2020, Beyaz Masa received complaints of almost a million which report problems ranging from broken pipes to buses running late. In addition, particularly thorough Twitter, irrelevant and political content is addressed to the municipality accounts which unnecessarily divert  attention of workers at Beyaz Masa. With all of these in mind, one can understand that even communicating the complaints to the relevant municipal enterprise would be time-consuming and inefficient. We already observe that the municipality is negatively evaluated over an open online complaint platform due to the inefficiency in complaint handling. 

### Project Goals 

By developing a topic classification tool for written complaints addressed to Istanbul Metropolitan Municipality, we aim to facilitate the sorting of irrelevant content in these texts and the communication of the complaints to the relevant municipal enterprises in a shorter time. Therefore, while the workload at the complaint desk will be reduced, complaints of residents will be redressed more quickly.

### Our Approach 

Our data sources were online written complaints and tweets which we scraped from the Web. We labeled the texts in line with the 5 labels we determined earlier. Through Natural Language Processing techniques, we converted complaint texts to vector format so that we could train and test 4 Machine Learning algorithms on these texts. At the end, we obtained a tool that could predict the class of any text via one of the trained algorithms.  